server:
  port: 8080
spring:
  application:
    name: pulsecommerce
  config:
    import:
      - optional:classpath:env.properties

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_CLOUD_NAME}